// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/api/handlers/services.go
//
// Generated by this command:
//
//	mockgen -source ./internal/api/handlers/services.go -destination ./internal/api/handlers/mock/handlers_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/BitCoinOffical/online-subscriptions/subscription-service/internal/domain/dto"
	models "github.com/BitCoinOffical/online-subscriptions/subscription-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
	isgomock struct{}
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionService) CreateSubscription(ctx context.Context, arg1 *dto.SubscriptionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CreateSubscription(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CreateSubscription), ctx, arg1)
}

// DeleteSubscriptions mocks base method.
func (m *MockSubscriptionService) DeleteSubscriptions(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptions", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptions indicates an expected call of DeleteSubscriptions.
func (mr *MockSubscriptionServiceMockRecorder) DeleteSubscriptions(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptions", reflect.TypeOf((*MockSubscriptionService)(nil).DeleteSubscriptions), ctx, id)
}

// FullUpdateSubscriptionsById mocks base method.
func (m *MockSubscriptionService) FullUpdateSubscriptionsById(ctx context.Context, arg1 *dto.SubscriptionDTO, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullUpdateSubscriptionsById", ctx, arg1, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// FullUpdateSubscriptionsById indicates an expected call of FullUpdateSubscriptionsById.
func (mr *MockSubscriptionServiceMockRecorder) FullUpdateSubscriptionsById(ctx, arg1, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullUpdateSubscriptionsById", reflect.TypeOf((*MockSubscriptionService)(nil).FullUpdateSubscriptionsById), ctx, arg1, id)
}

// GetSubscriptions mocks base method.
func (m *MockSubscriptionService) GetSubscriptions(ctx context.Context, limit, offset int) ([]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptions", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptions indicates an expected call of GetSubscriptions.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptions", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptions), ctx, limit, offset)
}

// GetSubscriptionsById mocks base method.
func (m *MockSubscriptionService) GetSubscriptionsById(ctx context.Context, id int) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsById", ctx, id)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsById indicates an expected call of GetSubscriptionsById.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionsById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsById", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionsById), ctx, id)
}

// GetSubscriptionsFilter mocks base method.
func (m *MockSubscriptionService) GetSubscriptionsFilter(ctx context.Context, from, to, user_id, service_name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsFilter", ctx, from, to, user_id, service_name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsFilter indicates an expected call of GetSubscriptionsFilter.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionsFilter(ctx, from, to, user_id, service_name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsFilter", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionsFilter), ctx, from, to, user_id, service_name)
}

// UpdateSubscriptionsById mocks base method.
func (m *MockSubscriptionService) UpdateSubscriptionsById(ctx context.Context, arg1 *dto.PatchSubscriptionDTO, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionsById", ctx, arg1, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionsById indicates an expected call of UpdateSubscriptionsById.
func (mr *MockSubscriptionServiceMockRecorder) UpdateSubscriptionsById(ctx, arg1, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionsById", reflect.TypeOf((*MockSubscriptionService)(nil).UpdateSubscriptionsById), ctx, arg1, id)
}
