// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/interfaces/http/services/repositories.go
//
// Generated by this command:
//
//	mockgen -source ./internal/interfaces/http/services/repositories.go -destination ./internal/interfaces/http/services/mock/service_mock.go -package mocks_services
//

// Package mocks_services is a generated GoMock package.
package mocks_services

import (
	context "context"
	reflect "reflect"

	models "github.com/BitCoinOffical/online-subscriptions/subscription-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepo is a mock of SubscriptionRepo interface.
type MockSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepoMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepoMockRecorder is the mock recorder for MockSubscriptionRepo.
type MockSubscriptionRepoMockRecorder struct {
	mock *MockSubscriptionRepo
}

// NewMockSubscriptionRepo creates a new mock instance.
func NewMockSubscriptionRepo(ctrl *gomock.Controller) *MockSubscriptionRepo {
	mock := &MockSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepo) EXPECT() *MockSubscriptionRepoMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionRepo) CreateSubscription(ctx context.Context, sub *models.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionRepoMockRecorder) CreateSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionRepo)(nil).CreateSubscription), ctx, sub)
}

// DeleteSubscriptions mocks base method.
func (m *MockSubscriptionRepo) DeleteSubscriptions(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptions", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptions indicates an expected call of DeleteSubscriptions.
func (mr *MockSubscriptionRepoMockRecorder) DeleteSubscriptions(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptions", reflect.TypeOf((*MockSubscriptionRepo)(nil).DeleteSubscriptions), ctx, id)
}

// FullUpdateSubscriptionsById mocks base method.
func (m *MockSubscriptionRepo) FullUpdateSubscriptionsById(ctx context.Context, sub *models.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullUpdateSubscriptionsById", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// FullUpdateSubscriptionsById indicates an expected call of FullUpdateSubscriptionsById.
func (mr *MockSubscriptionRepoMockRecorder) FullUpdateSubscriptionsById(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullUpdateSubscriptionsById", reflect.TypeOf((*MockSubscriptionRepo)(nil).FullUpdateSubscriptionsById), ctx, sub)
}

// GetSubscriptions mocks base method.
func (m *MockSubscriptionRepo) GetSubscriptions(ctx context.Context) ([]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptions", ctx)
	ret0, _ := ret[0].([]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptions indicates an expected call of GetSubscriptions.
func (mr *MockSubscriptionRepoMockRecorder) GetSubscriptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptions", reflect.TypeOf((*MockSubscriptionRepo)(nil).GetSubscriptions), ctx)
}

// GetSubscriptionsById mocks base method.
func (m *MockSubscriptionRepo) GetSubscriptionsById(ctx context.Context, id int) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsById", ctx, id)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsById indicates an expected call of GetSubscriptionsById.
func (mr *MockSubscriptionRepoMockRecorder) GetSubscriptionsById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsById", reflect.TypeOf((*MockSubscriptionRepo)(nil).GetSubscriptionsById), ctx, id)
}

// GetSubscriptionsFilter mocks base method.
func (m *MockSubscriptionRepo) GetSubscriptionsFilter(ctx context.Context, from, to, user_id, service_name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionsFilter", ctx, from, to, user_id, service_name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionsFilter indicates an expected call of GetSubscriptionsFilter.
func (mr *MockSubscriptionRepoMockRecorder) GetSubscriptionsFilter(ctx, from, to, user_id, service_name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionsFilter", reflect.TypeOf((*MockSubscriptionRepo)(nil).GetSubscriptionsFilter), ctx, from, to, user_id, service_name)
}

// UpdateSubscriptionsById mocks base method.
func (m *MockSubscriptionRepo) UpdateSubscriptionsById(ctx context.Context, sub *models.PatchSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionsById", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionsById indicates an expected call of UpdateSubscriptionsById.
func (mr *MockSubscriptionRepoMockRecorder) UpdateSubscriptionsById(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionsById", reflect.TypeOf((*MockSubscriptionRepo)(nil).UpdateSubscriptionsById), ctx, sub)
}
